text_cleanning <- function(value) {
  ines <- as_tibble(strsplit(value, "\n", fixed = TRUE)[[1]])
  content <- str_replace(ines, "\\.\\s+\\.", "..")
  content <- str_replace(content, "^(\\p{L})\\s", "")
  content <- str_replace_all(content, "\\[|\\]|\\}|\\{|\\!", "|")
  content <- str_replace(content, "^\\s*\\|", "")
  content <- str_replace(content, "\\|\\|", "|")
  content <- str_replace(content, "(?<=\\..)1", "|")
  content <- str_replace_all(content, "(\\.{2,})\\s*([A-Za-z0-9])", "\\1|\\2")
  content <- str_trim(content, side = "left")
  content <- str_replace(content, "(.)(dem)", "i\\2")
  arg <- str_split(content, "(?<!\\d)\\.+(?!\\d)")
  arg <- as.character(arg)
  arg <- str_replace_all(arg, "\", \"", "")
  arg <- str_replace_all(arg, "^c\\(\"|\"\\)$", "")
  separate_wider_delim(arg, delim = "|", names_sep = "", too_few = "align_start")
}
